name: Create Alfred Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Alfred workflow
        id: builder
        run: |
          cd ente-totp
          python -m venv .venv
          source .venv/bin/activate
          ./build.sh
        env:
          WORKFLOW_VERSION: ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.builder.outputs.OUTPUT_FILE }}